[package]
name = "trf_disease_repeats"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
indicatif = "0.18.3"
rayon = "1.11.0"
sysinfo = "0.37.2"
